version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: rajababu
      POSTGRES_PASSWORD: techmedaddy
      POSTGRES_DB: rugasdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: node:18
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://rajababu:techmedaddy@postgres:5432/rugasdb
    command: sh -c "npm install && npx prisma generate && npm run dev"

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3076:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000/api
    command: sh -c "npm install && npm run dev"

volumes:
  pgdata:
